// Netlify build script - generates config.js from environment variables
const fs = require('fs');
const path = require('path');

// Get API_BASE_URL from Netlify environment
const apiBaseUrl = process.env.API_BASE_URL || 'http://localhost:3000';

// Generate config.js file
const configContent = `// ==========================================
// VYGC CONFIGURATION - Auto-generated by Netlify
// ==========================================

window.API_BASE_URL = '${apiBaseUrl}';
console.log('✅ API_BASE_URL configured:', '${apiBaseUrl}');
`;

const configPath = path.join(__dirname, 'config.js');
fs.writeFileSync(configPath, configContent);

console.log('✅ Generated config.js with API_BASE_URL:', apiBaseUrl);
